version: '2'
services:
    bookingmicroservice-mongodb:
        container_name: bookingmicroservice-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BookingMicroservice/mongodb/:/data/db/
