version: '2'
services:
    bookmicroservices-cassandra:
        container_name: bookmicroservices-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/BookMicroservices/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    bookmicroservices-cassandra-node:
        image: cassandra:2.2.7
        links:
            - bookmicroservices-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    bookmicroservices-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: bookmicroservices-cassandra-migration
        links:
            - bookmicroservices-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
