version: '2'
services:
    bookmicroservices-mongodb:
        container_name: bookmicroservices-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BookMicroservices/mongodb/:/data/db/
